all:
  children:
    pcs
    nfs

pcs:
  hosts:
    node1:
      ansible_host: 127.0.0.1 
      ansible_port: 2222 
      ansible_ssh_private_key_file: ./.vagrant/machines/node1/virtualbox/private_key

    node2:
      ansible_host: 127.0.0.1 
      ansible_port: 2200 
      ansible_ssh_private_key_file: ./.vagrant/machines/node2/virtualbox/private_key

    node3:
      ansible_host: 127.0.0.1
      ansible_port: 2201
      ansible_ssh_private_key_file: ./.vagrant/machines/node3/virtualbox/private_key
nfs:
  hosts:
    nfs1:
      ansible_host: 127.0.0.1
      ansible_port: 2202
      ansible_ssh_private_key_file: ./.vagrant/machines/nfs1/virtualbox/private_key
